[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ntest"
version = "0.0.1"
authors = [{name="Noah Mingolelli"}]
license = "MIT"

[project.scripts]
ntest = "ntest:main"